# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./fbmessage
# Target is an application:  

FORMS += _billingmessage.ui 
IDLS += _billingmessage.ui 
HEADERS += billingmessage.h 
SOURCES += billingmessage.cpp \
           main.cpp 
