# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./server
# Target is an application:  

FORMS += _server.ui 
HEADERS += bserversocket.h \
           formserver.h \
           protokol.h 
SOURCES += bserversocket.cpp \
           main.cpp \
           formserver.cpp 
CONFIG += release \
warn_on \
qt \
thread \
x11
TEMPLATE = app
